apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-static-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi  
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.14
    path: "/export/volumes/static"
