apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
      - image: nginx
        name: test-pod-emptydir
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}